import { Button, Container, Typography } from "@mui/material";
import Navigation from "@/app/components/navigation";
import '../app/scss/main.scss';
import { useRouter } from 'next/router'

export const Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function MyApp({ Component, pageProps }) {
    const router = useRouter()
    const navigationSimple = ['/'].includes(router.pathname) ? false : true

    return (
        <main>
            <Navigation simple={navigationSimple} />

            <Container maxWidth="lg" sx={{ mt: 12 }}>
                <Component {...pageProps} />
            </Container>
        </main>
    )
}